apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo
  labels:
    app: canary-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: canary-demo
      # Add a conditional label for Harness Canary deployments
      {{ if .Values.harnessTrack }}
      harness.io/track: {{ .Values.harnessTrack }}
      {{ end }}
  template:
    metadata:
      labels:
        app: canary-demo
        # Add a conditional label for Harness Canary deployments
        {{ if .Values.harnessTrack }}
        harness.io/track: {{ .Values.harnessTrack }}
        {{ end }}
    spec:
      containers:
        - name: canary-demo
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "{{ .Values.image.tag }}"
