apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo
  labels:
    app: canary-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
        - name: canary-demo
          # This now pulls the image from the values.yaml file.
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              # The same value is passed as an environment variable.
              value: "{{ .Values.image.tag }}"
