# This file defines the values for our Kubernetes manifests.
image:
  repository: ganesh243/canary-app
  tag: "<+artifacts.primary.tag>"

# This variable is now set by Harness internally.
harnessTrack: "{{ .Values.harnessTrack }}"
